---
title: "About Us"
author: "Muhammad Raditya Nayatama"
date: "1/23/2022"
output: html_document
---

## About us

### Background

We are the **CRC App Team** (Group T). We created this app to help people over 35 years of age determine whether they are at risk of a **Cardiovascular disease** or not. We came up with the idea to make the app from researching on what was the most frequent cause of death. Then we found out that **Cardiovascular disease (CVD)** was one of the main causes of death around the world. From then, our group decided to develop an app that can assess if someone is at risk of **CVD** called the **Cardiovascular Risk Checker**.

Link to our github: https://github.com/Md-Al-Aubasani/CRCwia1007

### Members

##### **Leader:**
Name         : Mohammed Sayeed Mohsin Al Aubasani

Matric       : S2102848

##### **Member 1:**
Name         : Abdulrahman Mohammed Omar Al-Tamimi

Matric       : S2001699

##### **Member 2:**
Name         : Shadman Iztihad Bhuiya

Matric       : S2102789

##### **Member 3**
Name         : Muhammad Raditya Nayatama

Matric       : S2112040


